### ISSUE TITLE
AzureMigrateAppliance do not have "Azure connectivity"

### ISSUE THREAD

**Issue by reduards** [microsoft/MCW-Line-of-business-application-migration#102]
Running into an issue where the pre-req fails to check for connectivity to Azure. 

URL: https://graph.windows.net/

Error:
"The check failed as the URL https://graph.windows.net/ is not reachable and has returned an error: "401 : Unauthorized".

This can happen if you have not whitelisted the required URLs for connectivity to Azure or have not provided the correct proxy details in the configuration manager to access the URLs."

Lab guide simply says "it should pass the test automatically"

Best Regards,
Rasmus

**Comment by reduards** [comment]
The fix seem to be to skip that connectivity part and just put in the Azure Migrate key directly, this will enforce an update that will solve the problem for you! Make sure to not put your project Azure Migrate Project in Sweden, that didn't work.

**Comment by codingbandit** [comment]
Thank you for this issue, @reduards - I have identified the issue as the Azure Migrate Appliance VHD becoming too far out of date. I am currently working on getting this updated so that a more recent version is deployed with the HyperV host VM.

I am glad you found a work around in the meantime!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #103
