### ISSUE TITLE
WDS trainer presentation

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Line-of-business-application-migration#13]
@mwasham @jeff-opsgility
Slide 11, the 3 icons on top are built images, not a single, flat image.  Image 3 is missing an alt-text.  Changes have been made to the PPT, please make sure to update this version.  Thanks

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Adding for visibility

**Comment by jtuliani** [comment]
Fixed in 'may-2019-fixes' branch

**Comment by DawnmarieDesJardins** [comment]
Resolved with May 2019 fixes PR
