### ISSUE TITLE
Hands on lab step-by-step

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Line-of-business-application-migration#14]
@mwasham @jeff-opsgility
Line 95, solution architecture image has no alt-text.

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Adding for visibility

**Comment by jtuliani** [comment]
Fixed in may-2019-fixes branch

**Comment by DawnmarieDesJardins** [comment]
Resolved with may 2019 fixes PR.
