### ISSUE TITLE
Hands on Lab step by step - DHCP and sync time issue service during startup

### ISSUE THREAD

**Issue by szakaria** [microsoft/MCW-Line-of-business-application-migration#16]
The post reboot powershell hanged after resources were deployed in Azure.   This was consistent until we restarted the DHCP service and sync service.  Reran the post reboot script and issue was resolved.

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Please review & advise.

**Comment by jtuliani** [comment]
We have seen issues with the post reboot script downloads failing or being corrupted, especially when deploying multiple labs in parallel. I am engaged with the Azure Storage team and we are investigating.

I'm not aware of any link between this issue and the DHCP service or sync service, would appreciate any evidence you have that the problem may be related to those services.

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Adding for visibility

**Comment by jtuliani** [comment]
To address the post reboot script hang issue, which we saw being created by the ZIP file downloads, we have changed the post reboot script to use AzCopy v10 instead of v8. This seems to fix the issue (we've not seen it since the change). The change is in the 'may-2019-fixes' branch.

**Comment by DawnmarieDesJardins** [comment]
Resolved with may 2019 fixes PR.
