### ISSUE TITLE
Application -> Database interaction

### ISSUE THREAD

**Issue by justinjakowski** [microsoft/MCW-Line-of-business-application-migration#17]
Installed this lab and was trying to view the interaction between the web server and the db server.  installed the dependency agent(s) on both and even after checking customers in and out I was unable to view any web to db server dependencies in ServiceMap.  We should probably deploy an application that actually has app -> db interaction.

**Comment by ciphertxt** [comment]
For this particular deployment, you need the dependency agent on Web1, Web2, and the SQL instance. Web1 is a web server (only serves port 80) which communicates to a DB through WCF web service hosted on Web2 (port 2901). While Web1 never talks directly to the DB, Web2 does.

**Comment by DawnmarieDesJardins** [comment]
@justinjakowski 
Hi Justin,
Did this solve the trouble you were having?  May we close this issue out?
Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  @justinjakowski please reopen if needed.
