### ISSUE TITLE
Before HOL - Task 1: Deploy on-premises environment

### ISSUE THREAD

**Issue by tylormerck** [microsoft/MCW-Line-of-business-application-migration#19]
I am finding that change #18 has broken the deploy to Azure button for the workshop. Prior version works if you copy the prior link and paste manually into a new tab.

Old link:
![image](https://user-images.githubusercontent.com/23509524/60614640-ea1bfe80-9d92-11e9-842f-c958d2e08b95.png)

New link in this change: 
![image](https://user-images.githubusercontent.com/23509524/60614692-07e96380-9d93-11e9-87d9-93e4474032f1.png)

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @mwasham 
Hello, please review and advise.
Thanks, Dawnamrie

**Comment by jtuliani** [comment]
Fixed. Since the existing button was already broken, and I was making no other changes, I took the liberty of committing the fix directly to master rather than submitting a PR.
