### ISSUE TITLE
August 2019 - content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Line-of-business-application-migration#20]
This workshop is scheduled for an August update.  Please provide comments and feedback below.

Suggested updates:
Update to Azure Migrate v2 - It includes integration with a much wider range of third-party solutions, and also includes migration support for Hyper-V.
Recommended solution for Hyper-V migration, rather than using ASR.

**Comment by getazureready** [comment]
The Discovered items blade that appears after completing the assessment in the Azure portal, does not show Dependencies column in the details page. Has the dependency visualization changed in Azure?

**Comment by jtuliani** [comment]
There have been changes, and I'm addressing them in the forthcoming updates.
Look under 'Discovered Servers' (in the Azure Migrate: Migration Assessment panel) instead. The Dependencies column should be there.
However, there is a bug which means sometimes it doesn't show. I'm in discussions with the PG about that. You can still access the dependency visualization by going into an existing server group in that case.

**Comment by DawnmarieDesJardins** [comment]
@jtuliani 
Hi Jonathan - Please see PR #21 - review and include in your current update as needed.
Thanks!

**Comment by jtuliani** [comment]
Will do, thanks

**Comment by DawnmarieDesJardins** [comment]
Closing issue with the August 2019 update PR merge.
