### ISSUE TITLE
HTML Lab Guide - Screenshots not appearing 

### ISSUE THREAD

**Issue by Abhishekpathania01** [microsoft/MCW-Line-of-business-application-migration#23]
Hi, 

Could you please review the HTML Lab guide, something wrong with the screenshots. No screenhots are showing up due to some reasons.  

Thanks, 
Abhishek

**Comment by DawnmarieDesJardins** [comment]
Thanks Abhishek - we are looking into this.

**Comment by DawnmarieDesJardins** [comment]
@Abhishekpathania01 
Hi Abhishek!  I reran the HTML script and, it took a few minutes, but I see all images now.  If waiting doesn't work, please clear your cache and try again.

**Comment by Abhishekpathania01** [comment]
Sure @Dawnmarie DesJardins (GP Strategies Corporation)<mailto:v-dadesj@microsoft.com> I’ll check this and let you know.

Thanks for your quick help.


Thanks & Regards,
Abhishek Pathania
[cid:image002.png@01D57325.944742E0]

**Comment by DawnmarieDesJardins** [comment]
No further contact, closing issue as resolved.

**Comment by Abhishekpathania01** [comment]
@DawnmarieDesJardins Sorry for responding late. 
I still have same problem, cleared my cache/ data ( also tried to view HTML Guide inside a fresh VM to re-confirm.
Instead of images, I can see "screenshot of the itemname"
![image](https://user-images.githubusercontent.com/38715522/65805973-3c5b9880-e1a5-11e9-914e-d6dddb933556.png)

**Comment by DawnmarieDesJardins** [comment]
@Abhishekpathania01 
Thanks for letting me know.  Mine have disappeared again as well.  Reopening issue and assigning it to @paulopsgility and @mwasham 

I've rerun the HTML with no change.  Images in the WDS documents are there, missing from Before HOL & Step-by-step guides.  Please verify image coding.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  HTML script has been rerun and I verified images are showing.
Thank you!
