### ISSUE TITLE
Update instructions for creating a Migrate project and ask users to give a unique name for the project (may be use their initials)

### ISSUE THREAD

**Issue by snehaamicrosoft** [microsoft/MCW-Line-of-business-application-migration#27]
We (the Azure Migrate prodyuct team) are seeing a lot of failures in the create project flow with the project name ‘SmartHotelMigration’. We need the project name to be unique in a subscription, if a user tries to use two different resource groups but the same project name in the same subscription, the project creation will fail. To reduce the number of failures, we should ask the users to use their initials for project name vs a common name.

The instructions are in Task#1, Step #3 
![image](https://user-images.githubusercontent.com/20218418/66892521-8d72e580-f009-11e9-99d9-8606c5a07f0a.png)

**Comment by paulopsgility** [comment]
@snehaamicrosoft We generally write these to be run in a users subscription, not a shared subscription. That being said, we have no control over how these are used. Is this causing some kind of issue? Or just failures?

**Comment by paulopsgility** [comment]
@snehaamicrosoft Never mind, easy fix. I have added a note to uniquify the migration project name when using a shared subscription. 

Fixed in pr #26
