### ISSUE TITLE
Exercise 3 - Task 9 - RDP Instructions - Modification Required

### ISSUE THREAD

**Issue by AErmie** [microsoft/MCW-Line-of-business-application-migration#28]
The steps in Exercise 3: "Migrate the application and web tiers using Azure Migrate: Server Migration", 
[Task 9: "Post-migration steps"](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-9-post-migration-steps) need correcting, as you are instructed to RDP to each VM. However, as you follow the guide, you only have a single Public IP Address assigned to the UbuntuWAF VM. 

So essentially, you have to repeat the steps as mentioned in [Task 8: Configure the public IP address and test the SmartHotel application](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-8-configure-the-public-ip-address-and-test-the-smarthotel-application), and associate, de-associate, re-associate the one and only Public IP Address with each VM, in order to complete the steps listed in Task 9; namely install the Azure Virtual Machine Agent (VM Agent) on each of the migrated Azure VMs.

It's a minor issue, but the instructions are not clear for someone that may be new to Azure and not realize they need to do this.

**Comment by paulopsgility** [comment]
@AErmie Thanks for the feedback, we'll take a look at it. It is normal to give detailed instruction the first time around and then be brief in follow-on tasks where users are doing the same thing. We'll review it though.

**Comment by AErmie** [comment]
I can understand/appreciate that. It just wasn't obvious that we had to switch the Public IP Address association between all the systems to complete the task.

**Comment by paulopsgility** [comment]
OK, I am going to mark this as an enhancement so we can re-evaluate this at the next update.

**Comment by jtuliani** [comment]
Addressed in mar-2020-updates. Rather than add a public IP to give access to the VMs to install the agent, I used Azure Bastion.
