### ISSUE TITLE
January 2020 - content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Line-of-business-application-migration#31]
This workshop is scheduled for a January 2020 content update.  Please review open issue #28 and PR #30 and give your suggestions for further changes recommended for SME review.

**Comment by jtuliani** [comment]
Suggestions:

LAB
1. Incorporate issues #28, #32 
2. Update screenshots/lab guide to reflect any changes (e.g. addition of 'Discovery source' when starting a Migration Assessment)
3. Update to latest version of migration appliance
4. Fix comment re suggestion text referring to ASR when reviewing Unsupported Boot Type error in migration assessment (MS doc is now fixed)
5. SQL VM tries to install updates, and also complains about trusted sites when downloading MMA/DA - fix
6. Dependency visualization instructions say to copy Linux links, but they're not used - remove
7. After installing MMA/DA and generating traffic, we go on to viewing the dependency visualization. Need to refresh the browser (not just the blade) for the View Dependencies button to appear
8. DB creation experience has changed in portal - update instructions
9. DMS creation experience has also changed - update instructions
10. Update to latest DMA (e.g. includes 'Assessment type' drop down, new)

WDS:
1. Deemphasise EA discount in WDS
2. Address PR #30 
3. In Trainer Guide, clarify that Mobility Service (deployed on migrated VMs) is not needed for Hyper-V (text currently suggests it's always needed in the agent-based model).
4. Trainer Guide states physical server assessment not supported in Azure Migrate. It's actually now in Preview.

**Comment by DawnmarieDesJardins** [comment]
*UPDATE* 
The January 2020 update has been postponed.  Not closing this issue as the comments above are excellent.  Marking as an enhancement so we can revisit when update continues.

**Comment by jtuliani** [comment]
Thanks. We should for sure also address #33, it's definitely a universal pain point for students completing the lab using anything other than a US keyboard.

**Comment by paulopsgility** [comment]
Closing this. Superseded by issue #38
