### ISSUE TITLE
Updated DMA download

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Line-of-business-application-migration#32]
One quick observation – On SQL server VM of the host the DMA is already installed and it is older version. The older version of DMA do not have the facility to upload the DB assessment output to Azure. You may wan to change the DMA version to latest.
 (Kunal, 16 Nov 2019)

**Comment by AErmie** [comment]
Also, the updated DMA version won't install without .NET Framework 4.7.2 being installed (which you have to download manually/in offline install option) to get it to work.

**Comment by jtuliani** [comment]
Lab guide has you download and install DMA on the SmartHotel host, not the SQL VM. No need to go looking for it on the SQL VM, and also addresses the .NET Framework issue.

**Comment by anassql** [comment]
To assess the on-premises database using Data Migration Assistant we had followed all the steps perfectly but we stopped in point 16 (Ex2-Task4), we did install the DMA and create the assessment but we still don't get the button "upload to azure migrate"

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @jtuliani 
Reopening issue to review/address comment above

**Comment by DawnmarieDesJardins** [comment]
Apologies, re-closing.  New/same issue was opened.  See #39
