### ISSUE TITLE
Update VM Password to support VM access over HTTP Feature

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Line-of-business-application-migration#33]
@DawnmarieDesJardins - In exercise 1 task 3 step 11 https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-3-configure-the-azure-migrate-appliance , we have to provide Hyper-v host details where defined password in lab guide is  demo@pass123 , 
We (Spektra Systems) are providing VM access over HTTP for this lab, which won't support '@' in the VM Password. Can you please update the VM password from 'demo@pass123' to **demoPassword1!**

**Comment by jtuliani** [comment]
Agree we should eliminate the '@' character from across the entire lab at the next scheduled update. It is for sure a pain point.

**Comment by paulopsgility** [comment]
We will review this at the next update.

**Comment by jtuliani** [comment]
Addressed in mar-2020-updates. New password is demo!pass123 (used everywhere).
