### ISSUE TITLE
SQL License Expiry Issue

### ISSUE THREAD

**Issue by AErmie** [microsoft/MCW-Line-of-business-application-migration#34]
Hey team,
When I delivered this workshop for a Partner last week, there were issues with the database server. Some students reported that they were prompted because the SQL license was expired. This apparently caused the data that had been pre-loaded, to disappear (or not be accessible); and thus caused issues with completing the lab.

**Comment by paulopsgility** [comment]
Thanks @AErmie we are looking into this.

**Comment by paulopsgility** [comment]
@AErmie I am not able to reproduce this issue. I just deployed the environment and I am able to access all the servers, the database is there and is populated, and the website works. 

Do you have any other information to help narrow this down?  If only SOME students experienced this then it is likely they are doing something wrong and I would like to have the lab updated to remove any confusion or ambiguity. The VMs are deployed from images so it isn't like one person would have an expired license and another person wouldn't.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no response for further information.  @AErmie - if you are still having trouble, please reopen as needed.
