### ISSUE TITLE
Info about line-of-business application

### ISSUE THREAD

**Issue by OZ2003** [microsoft/MCW-Line-of-business-application-migration#35]
Can you include in the documentation some info on the LOB application please?
Just to get a better understanding what are controls on the web page, what are the actions available and what is expected as a result of actions.
This will help students to verify LOB app functionality before HOL and after app migration.
As it is right now, it's just a black box and guessing is it working or not.

Thank you!

**Comment by jtuliani** [comment]
Will address in mar-2020-updates
