### ISSUE TITLE
Issues noticed with the Hyper-V VM

### ISSUE THREAD

**Issue by ravibak** [microsoft/MCW-Line-of-business-application-migration#37]
I wasnt able to debug much but noticed two issues
.
1) After the VM (Hyper-V machine simulating On-prem) was deployed, guest VMs were absent, seems like PostRebootConfigure.ps1 did not run (because schedule task was missing), I tried creating the task, rebooted the machine but guest VMs were not still not configured. Ran the PostRebootConfigure.ps1 manually, it configured all the VMs except the smarthotelSQL1.

2) I then manually imported the smarthotelSQL1 and associated configuration.

**Comment by jtuliani** [comment]
I'm having this problem too. The PowerShell scripts both run - they both generate transcript output files in C:\.   However the PostRebootConfigure.ps1 is existing early for some reason.  Investigating.

**Comment by paulopsgility** [comment]
This is fixed in the March 2020 update
