### ISSUE TITLE
Issues:- Not able to connect the hyper VM(Azure Migrate appliance) to internet.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Line-of-business-application-migration#40]
Exercise 1: TASK 3:- Configure the Azure Migrate appliance.

After importing the Azure Migrate appliance to hyper-v, the VM is not getting connected with the internet, Also the VM ip is not coming under the NAT Address space(192.168.0.1/24). I tried changing the VM IP but still it's not getting connected. Please take a look into that.

Thanks.

**Comment by jtuliani** [comment]
This has worked many times and there have been no changes in this area. Something is obviously amiss in your Azure Migrate appliance network configuration, based on the lack of connectivity and also the incorrect address space.

Please can you try again? Make sure you connect the Azure Migrate Appliance to the correct Hyper-V network switch (the AzureMigrateSwitch is set up for you already).

**Comment by sumitmalik51** [comment]
The switch is not showing as **AzureMigrateSwitch**, it has a different name **Default switch**. and all the other VM also connected with the same Switch.

**Comment by sumitmalik51** [comment]
Hi, This is issue resolved basically in the powershell script for creating Azure NAT switch commands was not working properly. Now i am able to connect the VM to Internet.

Thanks
