### ISSUE TITLE
Not able to get Nested Virtual Machine and Smarthotel page

### ISSUE THREAD

**Issue by vivekgupta8983** [microsoft/MCW-Line-of-business-application-migration#43]
Not able to get Nested Virtual Machine and also smart hotel webpage also not coming in Before the hands-on lab

**Comment by jtuliani** [comment]
Can you describe the issue in more detail? For example, does the template deployment show any errors?  Don't forget you will need to wait 75 minutes from the start of template deployment for the SmartHotel app to work (the template finishes faster, but there is still a lot of set up work that happens after that)

**Comment by vivekgupta8983** [comment]
after waiting upto 60 minutes then all working
