### ISSUE TITLE
October 2020 - Update Suggestions

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Line-of-business-application-migration#50]
This workshop is schedule for an update.  Please review current MCW and open issue #46 and provide your recommended changes below.

**Comment by dwnatwick** [comment]
Line of business application migration
H2 2020 Updates
Whiteboard Design Session
1.	Incorporate Landing Zones (in the context of Cloud Adoption Framework and Well Architected Framework) as part of the Whiteboard Design Session – request from Issue #46
Hands-On Lab
2.	Verify that Azure Migrate tasks are current based on August 2020 updates.
3.	The current lab misses the final migration step – cutting over production traffic from the old deployment to the migrated deployment. To add this step we suggest implementing a DNS-based switchover, so the same DNS name starts out pointing to the old app and ends the lab pointing to the new one. This provides the opportunity to make sure students understand the DNS issues related to switch-over, for example, setting a short TTL at the start of the process so cached DNS entries have time to expire.
The DNS hosting can be provided by Azure DNS – no issues there.
An open issue is whether to use a registered DNS domain name. This can be provided by Azure App Service Domains (there is no charge as long as the resource is deleted within 5 days). However, registering a domain name requires contact details to be filled in (name, address, email, etc – we suggest using generic Microsoft values e.g. 1 Microsoft Way)
Other requested items from Issue #46:
-	Linux content (RHEL and SLES) – We already have Linux OS in the WDS and HOL
-	MySQL or PostgreSQL OSS DB utilization – this requires re-engineering and re-design of database and apps in the HOL outside the allotted time given for enhancements.

**Comment by Tapper21** [comment]
Hello Please update the contents.. especially the database migration part.. We will be having an HOL event this month.. Thank you!

**Comment by DawnmarieDesJardins** [comment]
@Tapper21 
Thanks for reaching out.  We are in the process of updating this workshop.  A draft is currently in SME review and we should publish the update by EOD 11/20/20.

**Comment by zagruby** [comment]
When trying to accomplish Task 5: Configure dependency visualization, on point 3 - Configure OMS workspace I was getting error doing workspace deployment on deploying service map. "No registered resource provider found for location 'ANYLOCATIONHERE' and API version '2017-01-01-preview' for type 'solutions'. The supported api-versions are '2015-11-01-preview'."

Redeploying the template and changing values from:
```
"type": "Microsoft.OperationsManagement/solutions",
            "apiVersion": "2017-01-01-preview",
```

to:
```
"type": "Microsoft.OperationsManagement/solutions",
            "apiVersion": "2015-11-01-preview",
```

makes possible to deploy service map, however the preview of the map is not possible from the azure migrate: server assessment tab, but from the workspace directly. This is confusing for the workshop participants. However this looks more like Azure itself problem not the workshops.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #52
