### ISSUE TITLE
During Onprempart

### ISSUE THREAD

**Issue by RicGB** [microsoft/MCW-Line-of-business-application-migration#51]
During On Prem InstallatioVM, WAF etz......
I Asume this is not normal.

**Comment by jtuliani** [comment]
Hi @RicGB ...please can you clarify the issue you experienced? I'm not clear on the problem from the above. Thanks!

**Comment by RicGB** [comment]
Forget about any issue, everything is working fine, I notice you that scripting phase can be much longer than 1,15h in my case on second attempt was 3h or so. Thanks for answer and really good job Enviado desde Correo para Windows 10 De: Jonathan TulianiEnviado: jueves, 29 de octubre de 2020 11:02Para: microsoft/MCW-Line-of-business-application-migrationCC: RicGB; MentionAsunto: Re: [microsoft/MCW-Line-of-business-application-migration] During Onprempart (#51) Hi @RicGB ...please can you clarify the issue you experienced? I'm not clear on the problem from the above. Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dwnatwick** [comment]
Comment from @RicGB states that everything is working fine per comment on 5 days ago.  Closing this issue.
