### ISSUE TITLE
WBS doesn't link to HOL

### ISSUE THREAD

**Issue by thommck** [microsoft/MCW-Line-of-business-application-migration#53]
It would be much better if the hands on lab content linked to the whiteboarding session. At the moment they are about 2 different compaines/apps so it is a bit jarring for students to go from one to the other

**Comment by DawnmarieDesJardins** [comment]
@thommck 
Hi Thom, thanks for reaching out.  Can you give me a little more information please?  The lab and the WDS both use Fabrikam and the goal of the workshop is walking through a migration for the company.  We don't have the ability to take lab learners through difference scenarios so the WDS will typically discuss other possible solutions and the lab will follow one solution from beginning to end.  What are we missing for you?

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further correspondence from field.  Please reopen if needed.
