### ISSUE TITLE
Instruction need to be updated 

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-Line-of-business-application-migration#54]
Hi Team, 

Exercise 1, task 3 and step 10: When we login to register with Azure Migrate, it asks for code to login, for getting that code and entering need to update instructions. 

![image](https://user-images.githubusercontent.com/27498287/99932914-80cdce80-2d7f-11eb-9843-557a45dd6dec.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #56
