### ISSUE TITLE
Unable to find custom DNS settings for Private endpoint

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Line-of-business-application-migration#55]
1. [**Exercise 2 Task 5 and Step 6**](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-5-create-a-dms-migration-project): 
After creating the private endpoint **SmartHotel-DB-for-DMS** , I am not able to find the listed FQDN with an internal IP address.

![lob1](https://user-images.githubusercontent.com/52440474/100090266-ef428780-2e78-11eb-844a-8401251aa69d.png)

2. [**Exercise3 Task2 Step8**](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-2-create-a-virtual-network):
Facing the same issue for the private endpoint SmartHotel-DB-Endpoint.

![lob2](https://user-images.githubusercontent.com/52440474/100090534-4b0d1080-2e79-11eb-9a3a-ca7cf454ade9.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #56
