### ISSUE TITLE
Replace the UbuntuWAF with App gateway

### ISSUE THREAD

**Issue by manasvin** [microsoft/MCW-Line-of-business-application-migration#57]
Don't migrate ubuntuwaf but use a pre-created App gateway (WAFV2) to replace the WAF function

This new approach should support an optimized Migration (vs simpley lift+shift) alongside introducing the App gateway native service to the attendee.

Demo simplicity can be afforded by pre-creating the WAF using a new Public IP and the backend pool pointing to the LabVM (initially to support a templated creation). The backend pool can be amended easily within Ex3-Task 9 to point to the newly migrated VMs (smarthotelweb1, and smarthotelweb2). Azure migrate's Migration of ubuntu WAF need not be done in this scenario

Template file attached for Automated creation
[AppGwTemplate.zip](https://github.com/microsoft/MCW-Line-of-business-application-migration/files/5654548/AppGwTemplate.zip)

**Comment by DawnmarieDesJardins** [comment]
@manasvin
Thank you for your suggestion.  Marking this as an enhancement for review/discussion in our next scheduled update.
