### ISSUE TITLE
Pre Create the OMSworkspace 

### ISSUE THREAD

**Issue by manasvin** [microsoft/MCW-Line-of-business-application-migration#58]
Pre-create the OMS workspace in the lab so the Attendee just needs to select it. Image below (select instead of create) time saved about about 10-15mins (Ex 1 Task 5 Step 3)
![image](https://user-images.githubusercontent.com/18642248/101392600-de086a80-38bd-11eb-89ff-110bc8b2aa56.png)

Ex 2 Task 1 Step 1
![image](https://user-images.githubusercontent.com/18642248/101392888-3ccde400-38be-11eb-9a6c-f2a587b10135.png)

**Comment by DawnmarieDesJardins** [comment]
@manasvin
Thank you, labeling this as an enhancement for review/discussion in our next scheduled update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, simplifications made in latest update.
