### ISSUE TITLE
Pre-Create the Azure SQL database (exercise 2)

### ISSUE THREAD

**Issue by manasvin** [microsoft/MCW-Line-of-business-application-migration#59]
Precreate the Azure SQL database in Exercise 2 along with its private link. The pre-created database and private link can be reviewed and details of the server copied (to clipboard) for later use. 

To clarify this should will be an empty database.

This would contribute towards reducing the time to finish the lab and continue to support overall objective of the lab i.e. Infrastructure Migration

**Comment by DawnmarieDesJardins** [comment]
Labeling this as an enhancement for review/discussion in our next scheduled update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, simplifications made in latest update.
