### ISSUE TITLE
Simplify the lab with focus on migration outcomes

### ISSUE THREAD

**Issue by manasvin** [microsoft/MCW-Line-of-business-application-migration#60]
The lab does get quite lengthy for a **single day workshop**. Suggest simplification of the target solution with a focus on outcomes i.e. migration of on-prem infrastructure to cloud, preferably optimised using cloud PaaS workloads

1. keep one simple network with subnets or ...
     a. precreate all vnets with their peerings and private links (including bastion)
2. Precreate Storage accounts, OMS/log workspaces
3. Use portal UI instead of shell
4. Use Precreated app gateway instead of ubuntuwaf
5. focus on the Azure migrate narrative

**Comment by DawnmarieDesJardins** [comment]
Labeling this as an enhancement for review/discussion in our next scheduled update.
