### ISSUE TITLE
Ex 3 Database Connection is denied (for all attendees)

### ISSUE THREAD

**Issue by manasvin** [microsoft/MCW-Line-of-business-application-migration#61]
Did the lab start to end yesterday.

The database connection is denied from the SmartHotelVNet. (tested end of exercise 3, including by attendees)

Only way we could get it to work is to open the firewall to all IP ranges.  

Possible solution(s)- Ex3 Task 2 needs to include addition of firewall inclusion of the SmartHotelVNet VNET or... because the private link IP fails to resolve from the SmartHotelVNet to the private ip address (seen this happen as well)

**Comment by DawnmarieDesJardins** [comment]
Closing as complete with merge of PR #62
