### ISSUE TITLE
Lab Steps Improvement

### ISSUE THREAD

**Issue by mimanu** [microsoft/MCW-Line-of-business-application-migration#63]
Exercise 3 Task 2 - RG

Steps says use RG - SmartHotelDBRG but screenshot is different

![image](https://user-images.githubusercontent.com/41720328/103453096-49a0f480-4d11-11eb-81d7-f163c0a0c14c.png)

Creation of Storage

Option to choose gpv1 missing

![image](https://user-images.githubusercontent.com/41720328/103453108-72c18500-4d11-11eb-8627-f4fdd22df404.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #64
