### ISSUE TITLE
Pre-requsite scripts and Azure appliance vm image need to be updated, screenshots  changes for Azure Migrate UI required

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-Line-of-business-application-migration#66]
Hi, 

 * Once the environment is ready and we are importing the appliance vm, internet is not working in the vm
      * **Workaround**: rerun the DHCP code manually which is in custom script extension script of the vm and then turnoff and start the appliance vm is fixing the internet issue in appliance vm, so Appliance vm need to restored as part of pre-req and then we can run DHCP script again and restart the vm
 * Appliance vm version is 2.x.x and ther in no edge or chrome browser installed in the vm which is required to run teh discovery, internet explorer is not supported anymore. Please update the appliance vm version to latest **3.x.x**.
 *  Azure Migrate UI got changed in Azure, please update the screenshots in lab guide.
 *  Do we need to install OMS workspace in Hyper-v guest VM? 

Thanks,
Amit

**Comment by akn9050** [comment]
I have raised PR for Azure Migrate UI fixes
https://github.com/microsoft/MCW-Line-of-business-application-migration/pull/67

**Comment by akn9050** [comment]
I have raised PR for Azure Migrate UI fixes, there are more updates required in further tasks thsi PR is for Exercise 1 only 
PR: https://github.com/microsoft/MCW-Line-of-business-application-migration/pull/67

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #67
