### ISSUE TITLE
Issue with Azure Migrate

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Line-of-business-application-migration#71]
[Exercise 1 Task 3 Step 19](https://github.com/CloudLabs-MCW/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-3-configure-the-azure-migrate-appliance): After configuring the Azure Migrate appliance and successful initiation of discovery process from appliance vm, discovery process is stuck at **Discovery is in progress state** . The number of discovered servers value is not changed from 0 to 5 but the discovered server is visible under appliance page. Please find the attached below screenshots below for reference.

![1](https://user-images.githubusercontent.com/52440474/127456944-e944f5f8-4729-4745-a88e-bc736f86fd67.png)
![2](https://user-images.githubusercontent.com/52440474/127456957-b9ea6410-c037-4a89-bfa7-4f8ed3221d2e.png)

 
We have workshops scheduled for tomorrow. Can you please prioritize this and work on it??

**Comment by DawnmarieDesJardins** [comment]
@tejaswini972 
Hello!  I have our authors looking into this for you.  For future reference, we advise 5-10 business days for issue review and resolution.  Please make sure to test early so we can provide you with the best support.

**Comment by KitSkin** [comment]
We added an option to the end of Task 3 to manually import servers if the discovery process is taking too long or not happening in a reasonable fashion. This should allow the systems to be available if the discovery is not finding them in time.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  Instructions to manually import servers was moved up in instructions for learners.  Please reopen if this did not solve the issue.
