### ISSUE TITLE
Issue win Before hands-on-lab template

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Line-of-business-application-migration#74]
1. In [Before Hans-on-lab Task 1](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Line-of-business%20application%20migration.md#task-1-deploy-the-on-premises-environment-and-landing-zone), when we click on **Deploy to Azure** button as per the instruction, the template is being deployed and setting up the on-premises environment without landing zone resources as the template didn't include the nested template deployment of Landing zone.

2. [Smarthotelhost.json](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/Resources/SmartHotelHost.json) file has typo mistakes and when we try to deploy after fixing that it fails below error.

      **Deployment template validation failed: 'The template reference 'SmartHotelRG' is not valid: could not find template resource or resource copy with this name.**

Please look into this and provide a fix for it.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #75
