### ISSUE TITLE
Task 5 no longer matches UI

### ISSUE THREAD

**Issue by musicjunkieg** [microsoft/MCW-Line-of-business-application-migration#77]
Task 5, *Create a DMS Migration Project,* is incorrect. Following the instructions, one cannot find the appropriate place to create a private endpoint. I'm not even sure it's point to the correct Resource Group in the documentation.

**Comment by DawnmarieDesJardins** [comment]
Adding this to closed PR #76 for review/fix.

**Comment by musicjunkieg** [comment]
@DawnmarieDesJardins - do you want more? I have more. :-p

**Comment by DawnmarieDesJardins** [comment]
@musicjunkieg - we need to know if there are errors in the lab and people can't complete them, thank you.

**Comment by musicjunkieg** [comment]
Okay. The below is all a reference to **Exercise 2: Migrate the Application Database**

- Task 5 step 1 has the wrong resource group. It should be the **SmartHotelRG** instead of the **SmartHotelHostRG.** Additionally, since this is the first time we've accessed the database server in Azure in the lab, there should be a screenshot which shows the Resource Group and highlights the SQL database that needs to be selected. 
- In Step 5 of Task 5, the second image needs to be updated to show that there is a third field now that also references a resource group and instruction should be given regarding that:
![CleanShot 2021-09-28 at 15 12 27](https://user-images.githubusercontent.com/2382127/135172886-7b882fc6-93bb-4da0-82ad-24076a29ac9c.png)
- The image in Task 7 Step 1 shows an **Offline data migration,** and this is also reference in the text in step 1. It is now just **Data Migration.**
- Task 7 is missing a step as there is now an additional step in the migration process called "Select Databases. Information on how to move through this step should be added. 
![CleanShot 2021-09-28 at 15 01 24](https://user-images.githubusercontent.com/2382127/135173323-81a23ef5-bbca-4df5-900b-0187a4329ddc.png)

**Comment by DawnmarieDesJardins** [comment]
Thank you. We advise 5-10 business days to review/resolve issues but Kit is in the process of updating the images will have a fix for us in the next couple of days.
