### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by aper050** [microsoft/MCW-Line-of-business-application-migration#78]
Hello ! 
Is anybody can help about error below during hostdeployment : 

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"La machine virtuelle a signalé une erreur pendant le traitement de l'extension « CustomSciptExtension ». Message d'erreur : « Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'The string is missing the terminator: '.\r\n + CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException\r\n + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString\r\n \r\n' »\r\n\r\nPour plus d'informations sur la résolution des problèmes, accédez à https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}

**Comment by aper050** [comment]
![image](https://user-images.githubusercontent.com/91459381/135289808-bbc29328-7b0a-4037-90bc-3a458dde5f36.png)

**Comment by KitSkin** [comment]
Hi aper050,

There was a typo in the external storage entry the deploy was pointing at. This has been resolved now. If you redeploy, the script should execute successfully.

Thank you
