### ISSUE TITLE
Issue in Exercise 3

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Line-of-business-application-migration#79]
[Exercise 3 Task 8](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#exercise-3-migrate-the-application-and-web-tiers-using-azure-migrate-server-migration): The first step in this task instructs to navigate to application gateway then again a new **Overview** is added for the task and the next steps says to navigate the Ubuntu VM to configure the Public IP address. Seems like instructions related to application gateway are missing.

![lob-issue-06](https://user-images.githubusercontent.com/52440474/135469807-598c565c-c88b-4e6f-abed-0f8ac9ddb0b0.png)

In Task 8 Step 5, When I browse the **Ubuntu VM Ip** received the below error. 

![lob-issue-07](https://user-images.githubusercontent.com/52440474/135469845-6cc5bcfe-8cc6-4a5c-bf92-998676dc942c.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #80
