### ISSUE TITLE
Missing step in exercise 3

### ISSUE THREAD

**Issue by TrevorBarry** [microsoft/MCW-Line-of-business-application-migration#84]
Exercise 3 step 2 should involve creating a new vnet with two subnets. That's missing from this version of the lab. The current step 2 should then be step 3 etc.

The Learn on Demand version of this has all of the steps.

**Comment by dwnatwick** [comment]
@TrevorBarry.  There was a recent update to this lab that actually did remove some steps.  LODS may not have pulled these updates into their player.  Thank you.
