### ISSUE TITLE
Issue in Exercise 1 Task 5

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Line-of-business-application-migration#89]
[Exercise 1 Task 5 Step19](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-5-configure-dependency-visualization): As per the instruction I have executed the command `sh InstallDependencyAgent-Linux64.bin -s` to install the dependency agent for Linux virtual machine but it is failing with below error.

**Extraction of dependency agent failed. Installer may be corrupt.**

Attached the screenshot below for reference.

![lobi](https://user-images.githubusercontent.com/52440474/144248628-354313fc-b23d-417b-82ba-76e7c639bd32.png)

Please check on this issue asap as e have workshop scheduled for tomorrow..!!

**Comment by KitSkin** [comment]
Hi @tejaswini972, this appears to be an issue with a recent build of the InstallDependencyAgent-Linux64.bin of the VM Insights dependency agent.  We're reaching out to try to get this resolved quickly.

However, if this cannot be fixed before your class, you can proceed with the Windows systems Insights to see their dependencies and details. The details of the UbuntuWAF will just not be visible, but it should not interfere with further migration steps.

**Comment by DawnmarieDesJardins** [comment]
Updating issue for visibility.  Kit is working with the authors of the VM Insights doc to resolve the issue, please stand by.

**Comment by sumitmalik51** [comment]
FYI, This issue is resolved and can be closed. :)

**Comment by KitSkin** [comment]
Thank you for the update, @sumitmalik51 . I can concur that the install deployment is now working as expected on Ubuntu deployments that it was not working on before.

@tejaswini972 please re-download the updated version of the dependency agent currently posted and re-deploy.

Thank you,
-Kit
