### ISSUE TITLE
Issue in Exercise 3 Task 8

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Line-of-business-application-migration#90]
[Exercise 3 Task 8](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-8-configure-the-public-ip-address-and-test-the-smarthotel-application):  As per the instruction, when I browsed the **IP address** associated with the public IP address appGwPublicFrontendIp, **SmartHotel360** application is not loaded even after configuring the endpoint a instructed in task 2 to allow private, secure access to the SQL Database.

When I changed the **SmartHoteldb database server** Firewall settings as below then the application is loaded with customer data. But it should work with private endpoint with out allowing public access to the SQL Database.

1. `Deny public network access` to **No**
2. `Allow Azure services and resources to access this server` to **Yes**

Please look into this issue asap as we have workshops scheduled this week.

**Comment by KitSkin** [comment]
Hi @tejaswini972 , 

Did you ensure that you are integrating the Private Endpoint with the Private DNS during creation in [Exercise 3 Task 2, Step 4](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-2-create-a-private-endpoint)? This is required for the name resolution to divert to the Private Endpoint's IP.

If that is there, verify that the VM is resolving the name of the database server in [Task 7](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-7-configure-the-database-connection) by doing either `ping <databaseserver>.database.windows.net` or `nslookup <databaseserver>.database.windows.net` via that VM. Either command should come back with the private IP address of the endpoint (ie: 192.168.0.132 or similar).

If the system is resolving correctly and still getting the error, consider **restarting** the VM to flush all app's and DNS cache to see if they have an entry for the public IP address still in their local cache.

If after a restart it is still not resolve, try adding the virtual network's address space to the SQL Server's firewall and denying the public access again.  The default network address space starts at 192.168.0.0 and ends at 192.168.1.255.

Please let me know if any of these work or if you are continuing to have issues.

Thank you,
-Kit

**Comment by sumitmalik51** [comment]
Hey @KitSkin , sure will give it a try.

**Comment by tejaswini972** [comment]
Hi @KitSkin,

I have enabled the option to integrate the Private Endpoint with the Private DNS during creation.

As you mentioned I followed the below steps and the data is being loaded in the **SmartHotel application**.

1. Allowed the public access to the database.
2. Added the existing virtual network **(SmartHotelVNet)** with address space 192.168.0.0-192.168.1.255 in the Firewall settings.
3. Blocked the the public access to the database.

I just wanted to check adding the vnet address in the **Firewall settings** is expected even after creating the private endpoint..!!?

Thanks,
Tejaswini.

**Comment by KitSkin** [comment]
Hi Tejaswini,

Once the Private Endpoint is created, access from the Virtual Network should be implicit from the SQL server's perspective.  Any Network Security Groups (NSGs) should be the primary method for controlling access to and from the Private Endpoint.  However, having the entries in the SQL server's firewall settings should not cause conflicts.

If you do connect over the Public Address and then remove the public access, ensure the resources are no longer using the Public IP address and instead are resolving to the Private Endpoint.

Thank you,
-Kit

**Comment by tejaswini972** [comment]
.
