### ISSUE TITLE
SQL migration - information mismatch

### ISSUE THREAD

**Issue by gunnarsteing** [microsoft/MCW-Line-of-business-application-migration#91]
In the following step:

> On the Configuration tab enter the following configuration then select Review + create, then Create.

The text says:

> Virtual network: DMSvnet
> 
> Subnet: DMS (10.1.0.0/24)

But the screenshot below says:
https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/images/Exercise2/private-endpoint-3.png

**Comment by DawnmarieDesJardins** [comment]
@KitSkin - Hey Kit!  Any update on this one?

**Comment by KitSkin** [comment]
I've updated the image to correspond to the values in the text.  Generally speaking, if the text and image differ, use the text as it is usually the one changed more dynamically.  Regardless, please let us know if there is a discrepancy so we can correct it, and thank you for bringing it to our attention.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.
