### ISSUE TITLE
Facing issue in Exercise 3 Task 9 Step 8

### ISSUE THREAD

**Issue by kaminiwalunj** [microsoft/MCW-Line-of-business-application-migration#93]
When we navigate to the smarthotelweb1 blade. Under Operations, select Run command and run  "ipconfig" command, we do not get output. Please find the below-mentioned screenshot.
![image](https://user-images.githubusercontent.com/88807671/154526285-fe5ce2a0-8c4f-44f9-bf60-71f2976658a5.png)

but, if we login into the VM and run the same command on command prompt, we get output:
![image](https://user-images.githubusercontent.com/88807671/154526434-40043e12-3917-49bd-a676-ffd6fe9be591.png)

**Comment by DawnmarieDesJardins** [comment]
@kaminiwalunj 
Hello.  Please let us know if you were able to complete the lab with the author's advice above.

**Comment by DawnmarieDesJardins** [comment]
No further contact received from field, closing issue.  Please re-open if you're still having trouble.
