### ISSUE TITLE
SQL DB Server UI changes

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Line-of-business-application-migration#97]
In [Exercise 2 Task 4 Step 2](https://github.com/microsoft/MCW-Line-of-business-application-migration/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Line-of-business%20application%20migration.md#task-4-create-a-dms-migration-project): As per the instruction, **Private endpoint connections** options should be present under **Security** but it is not available right now as UI of SQL server has been changed.

<img width="340" alt="2022-05-13_13-26-30" src="https://user-images.githubusercontent.com/52440474/168237909-add396dc-fce3-4726-9f28-46af08478bbf.png">

To add a private endpoint, under Security we need to select **Networking** then **Private access** tab. Now, under Private endpoint connections click on **+ Private endpoint**.

<img width="540" alt="db2 1" src="https://user-images.githubusercontent.com/52440474/168237982-3dd0d3bd-08a1-4eb4-ab6f-2e7b927a25a2.png">

Instructions and screenshots are to updated in Exercise 2 and Exercise 3 regarding the same.

Could you please look into this and updated the instructions and screenshots accordingly??

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #98
