### ISSUE TITLE
AzM Config. Mgr. Step 3 SW Inventory & Dependencies does not work. 

### ISSUE THREAD

**Issue by danielinjesus** [microsoft/MCW-Line-of-business-application-migration#99]
![image](https://user-images.githubusercontent.com/42823007/231915186-f91c3614-883d-465e-81be-fb717a019a91.png)

Hi, I have tried multiple times of troubleshooting on the errors of not getting 1. Software Inventory 2. Dependencies.

It seems that Azure Migrate Configuration Manager Step 3 of SW inventory discovery is not a part of this HOL but I want to do it. 

Please guide me if there are any way that I can discovery SW inventory and dependencies so that I will be able to visualize dependency map. 

Thank you.

**Comment by danielinjesus** [comment]
![image](https://user-images.githubusercontent.com/42823007/231927917-ce18ded4-b1fc-4429-b2b0-7a1a9be378e4.png)
Adding Azure Migrate Configurate Page Screenshot for reference

**Comment by danielinjesus** [comment]
In addition, I can't know why the IP and OS of UbuntuWAF gets undiscovered though the OS version seems to be a version that can be discovered by the appliance.

**Comment by DawnmarieDesJardins** [comment]
@danielinjesus 
Closing this issue as we can only provide guidance on current content.  I am adding the enhancement label so your comments can be reviewed and discussed with SMEs the next time this workshop is updated.  Thank you.
